export const BEGIN_REQUEST_CALL = 'BEGIN_REQUEST_CALL';
export const REQUEST_CALL_ERROR = 'REQUEST_CALL_ERROR';

export const LOAD_ANIMALS_SUCCESS = 'LOAD_ANIMALS_SUCCESS';
export const UPDATE_ANIMAL_SUCCESS = 'UPDATE_ANIMAL_SUCCESS';
export const CREATE_ANIMAL_SUCCESS = 'CREATE_ANIMAL_SUCCESS';
export const REMOVE_ANIMAL_SUCCESS = 'REMOVE_ANIMAL_SUCCESS';

